title: Akymos.io
url: "https://akymos.io"

future: true

pagination:
  enabled: true
  per_page: 5
  permalink: '/page:num/'
  sort_reverse: true
  trail: 
    before: 2
    after: 2

markdown: kramdown

kramdown:
  parse_block_html: true

autopages:
  enabled: true
  tags: 
    layouts: 
      - autopage_tags.html
    enabled: true
    permalink: '/tag/:tag'
  categories:
    layouts:
      - autopage_cats.html
    enabled: true
    permalink: '/:cat'
    title: 'Posts about :cat'
  collections:
    enabled: false

jekyll_timeago:
  depth: 1

# Build settings
plugins:
  - jekyll-feed
  - liquid-md5
  - jekyll-postcss
  - jekyll-seo-tag
  - jekyll-paginate-v2
  - jekyll-timeago
  - liquid_reading_time
  - jekyll-sitemap

postcss:
  cache: false

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - package-lock.json
  - bin