title: Akymos.io
baseurl: "" 
url: "https://akymos.io"
github_username: akymos

future: true
show_excerpts: false

tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag

pagination:
  enabled: true
  per_page: 5
  permalink: '/blog/page:num/'
  sort_reverse: true
  trail: 
    before: 2
    after: 2

dash:
  social_links:
    - url: https://linkedin.com/in/matteocusinato
      icon: linkedin
      color: blue
    - url: https://github.com/akymos
      icon: github-square
      color: purple

autopages:
  enabled: true
  tags: 
    layouts: 
      - autopage_tags.html
    enabled: true
    permalink: '/tag/:tag'
  categories:
    layouts:
      - autopage_cats.html
    enabled: true
    permalink: '/:cat'
    title: 'Posts about :cat'
  collections:
    enabled: false

# Build settings
theme: jekyll-dash
comments: true
plugins:
  - jekyll-feed
  - liquid-md5
  - jekyll/tagging
  - jekyll-toc

gems:
  - jekyll-paginate-v2
